usuarios:
    resource: "@UsuariosBundle/Resources/config/routing.yml"
    prefix:   /

users:
    resource: "@UsersBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
